### ISSUE TITLE
Adaptive Embedding Aggregation Fusion module

### ISSUE THREAD

**Issue by wendongj** [HaoFengyuan/X-TF-GridNet#1]
Hi, dear, author, really thanks for sharing the result of this paper, it is an exciting work. I click this github page many times everyday to see if the code is updated.... I am confusing about Adaptive Embedding Aggregation Fusion module, in formula 13, as my understanding, Q is fixed embedding, it is one dimensional, K is reshaped into two dimensional, then how can them multiply together?

**Comment by HaoFengyuan** [comment]
Thank you for your attention! In this paper, we flat the $R^{\prime}_{b-1} \in \mathbb{R}^{D \times (T \times F)}$

**Comment by HaoFengyuan** [comment]
As described in our paper, the dimensions of K and V are (D, T×F), while Q can be interpreted as (1, D), resulting in a final output shape of (1, D). We utilized _nn.MultiheadAttention_ for this operation. Code updates will be made available once our paper is received.

**Comment by wendongj** [comment]
> As described in our paper, the dimensions of K and V are (D, T×F), while Q can be interpreted as (1, D), resulting in a final output shape of (1, D). We utilized _nn.MultiheadAttention_ for this operation. Code updates will be made available once our paper is received.

I see, thanks for your reply^_^
