### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by yezhangyinge** [HaoFengyuan/X-TF-GridNet#3]
Hello! I am reproducing your great work. And I want to know if you could offer me the pretrained model so that I can align my result with yours. And if convenient, could you please add my WeChat: yezhangyinge? Thanks~

**Comment by HaoFengyuan** [comment]
Hello, the Experimental setups we use are the same as SpEx+, you can directly compare the results in our paper for comparison. And if you still have questions, I will add your WeChat to talk more about it.

**Comment by haha010508** [comment]
could you share the pre-trained model with me? my WeChat is 15815571301, thank!!

**Comment by HaoFengyuan** [comment]
We release the model trained on the WHAMR! dataset, [there](https://github.com/HaoFengyuan/X-TF-GridNet/tree/main/exp).
