### ISSUE TITLE
How are the .scp files in the data folder obtained?

### ISSUE THREAD

**Issue by 12oneway** [HaoFengyuan/X-TF-GridNet#6]
Hello! Thank you for the author's open-source contribution! This is a very excellent work. I would like to ask how the .scp files in the data folder were obtained? I have looked at the dataset generation methods in the linked resources but couldn't find the answer. Could you please enlighten me? I would be very grateful!

**Comment by HaoFengyuan** [comment]
The scp file of the WSJ0-2mix, WHAM!, and WHAMR! datasets, e.g. the reference audio list, is the same as the SpEx+ and can be referred to [here](https://github.com/gemengtju/SpEx_Plus/tree/master/data/wsj0_2mix), while the scp file of the WSJ0-3mix and LIbri3Mix datasets, was randomly selected from the clean speech datasets and released in the hope that it will serve as a benchmark for future testing.
