### ISSUE TITLE
Inquiry regarding the re-implementation testset results 

### ISSUE THREAD

**Issue by aryanorb** [HaoFengyuan/X-TF-GridNet#7]
Hello,

First of all, thank you for sharing your GitHub code. It has been immensely helpful.

I recently re-implemented your work and evaluated it by measuring the SI-SDR on 4-second segments during validation. The results were almost identical to the values presented in your paper.

However, when I evaluated it on the WSJ0-2mix test set, I obtained an SI-SDR of 17.767 on the full-lengths, which is approximately 2 dB lower than the results reported in the paper of Table3. I was wondering if you could provide any suggestions or insights on how to address this discrepancy? I would greatly appreciate your guidance.

Thank you in advance for your help!

Best regards

**Comment by HaoFengyuan** [comment]
Hello, 

Thank you for your attention. 

May I ask if you are using the **_min_** version of the WSJ0-2mix dataset, which means that there is full-overlap between different speakers? 

Also, could you compare it with our open-source [demo](https://github.com/HaoFengyuan/X-TF-GridNet/tree/8499c57680d3224026ee31fae3d8989c1e3695bf/demo/WSJ0-2mix) to ensure that the dataset preparation process is correct?
